/**
 * Character Catalog
 * Available anime characters for profile creation
 */
const CHARACTER_CATALOG = [
  {
    id: 1,
    name: 'Ichika Amasawa',
    anime: 'Classroom of the Elite',
    rarity: 'SSR',
    description: 'Sharp, intelligent, and calculating',
    stats: {
      strength: 7,
      speed: 8,
      intelligence: 10,
      endurance: 7,
      charisma: 8,
    },
    image: 'https://via.placeholder.com/200?text=Ichika',
  },
  {
    id: 2,
    name: 'Rem',
    anime: 'Re:ZERO',
    rarity: 'SSR',
    description: 'Devoted and powerful',
    stats: {
      strength: 9,
      speed: 9,
      intelligence: 7,
      endurance: 8,
      charisma: 8,
    },
    image: 'https://via.placeholder.com/200?text=Rem',
  },
  {
    id: 3,
    name: 'Asuna',
    anime: 'Sword Art Online',
    rarity: 'SSR',
    description: 'Swift blade and determined warrior',
    stats: {
      strength: 8,
      speed: 9,
      intelligence: 7,
      endurance: 8,
      charisma: 7,
    },
    image: 'https://via.placeholder.com/200?text=Asuna',
  },
  {
    id: 4,
    name: 'Mikasa Ackerman',
    anime: 'Attack on Titan',
    rarity: 'SSR',
    description: 'Skilled fighter with unwavering resolve',
    stats: {
      strength: 9,
      speed: 10,
      intelligence: 6,
      endurance: 9,
      charisma: 5,
    },
    image: 'https://via.placeholder.com/200?text=Mikasa',
  },
  {
    id: 5,
    name: 'Zero Two',
    anime: 'Darling in the Franxx',
    rarity: 'SSR',
    description: 'Mysterious and powerful',
    stats: {
      strength: 9,
      speed: 8,
      intelligence: 7,
      endurance: 9,
      charisma: 9,
    },
    image: 'https://via.placeholder.com/200?text=Zero+Two',
  },
  {
    id: 6,
    name: 'Emilia',
    anime: 'Re:ZERO',
    rarity: 'SR',
    description: 'Kind-hearted and magically gifted',
    stats: {
      strength: 6,
      speed: 6,
      intelligence: 8,
      endurance: 7,
      charisma: 9,
    },
    image: 'https://via.placeholder.com/200?text=Emilia',
  },
  {
    id: 7,
    name: 'Mitsuri Kanroji',
    anime: 'Demon Slayer',
    rarity: 'SR',
    description: 'Flexible fighter with love-focused abilities',
    stats: {
      strength: 7,
      speed: 8,
      intelligence: 5,
      endurance: 8,
      charisma: 9,
    },
    image: 'https://via.placeholder.com/200?text=Mitsuri',
  },
  {
    id: 8,
    name: 'Raphtalia',
    anime: 'The Rising of the Shield Hero',
    rarity: 'SR',
    description: 'Loyal and combat-ready',
    stats: {
      strength: 8,
      speed: 7,
      intelligence: 6,
      endurance: 8,
      charisma: 7,
    },
    image: 'https://via.placeholder.com/200?text=Raphtalia',
  },
  {
    id: 9,
    name: 'Rin Tohsaka',
    anime: 'Fate Series',
    rarity: 'SR',
    description: 'Proud mage with powerful spells',
    stats: {
      strength: 5,
      speed: 7,
      intelligence: 9,
      endurance: 6,
      charisma: 8,
    },
    image: 'https://via.placeholder.com/200?text=Rin',
  },
  {
    id: 10,
    name: 'Chika Fujiwara',
    anime: 'Kaguya-sama: Love is War',
    rarity: 'R',
    description: 'Cheerful and unpredictable',
    stats: {
      strength: 4,
      speed: 6,
      intelligence: 7,
      endurance: 5,
      charisma: 10,
    },
    image: 'https://via.placeholder.com/200?text=Chika',
  },
];

module.exports = {
  CHARACTER_CATALOG,
  getCharacterById: (id) => CHARACTER_CATALOG.find(c => c.id === id),
  getCharacterByName: (name) => CHARACTER_CATALOG.find(c => c.name.toLowerCase() === name.toLowerCase()),
};
